# Generated by Django 2.0.1 on 2018-01-13 05:16

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('short_name', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='security_security_created_related', related_query_name='security_securitys_created', to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.Exchange')),
                ('modified_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='security_security_modified_related', related_query_name='security_securitys_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='security_security_owner_related', related_query_name='security_securitys_owner', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.SecurityType')),
            ],
            options={
                'verbose_name': 'security',
                'verbose_name_plural': 'securities',
                'db_table': 'security',
            },
        ),
    ]
