# Generated by Django 2.0.1 on 2018-01-13 05:16

import common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_exchange_created_related', related_query_name='dictionary_exchanges_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_exchange_modified_related', related_query_name='dictionary_exchanges_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_exchange_owner_related', related_query_name='dictionary_exchanges_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_securitytype_created_related', related_query_name='dictionary_securitytypes_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_securitytype_modified_related', related_query_name='dictionary_securitytypes_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_securitytype_owner_related', related_query_name='dictionary_securitytypes_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Type',
                'verbose_name_plural': 'Security Types',
                'db_table': 'dictionary_security_type',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('entry', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_system_created_related', related_query_name='dictionary_systems_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_system_modified_related', related_query_name='dictionary_systems_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.SET(common.models.UserUtils.get_recycle_user), related_name='dictionary_system_owner_related', related_query_name='dictionary_systems_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System',
            },
        ),
    ]
